### ISSUE TITLE
Some mods that add particle does not working on dedicated server, but singleplayer world does work

### ISSUE THREAD

**Issue by liangmoe** [Sinytra/Connector#1012]
### Minecraft version

1.20.1

### Describe the bug

Fabric mod that adds particle does not work on dedicated server

### Steps to reproduce

1. Install some mods that add particle with sinytra
2. Messing around join singleplayer world and dedicated server world
3. see the differences
...

### Logs

https://mclo.gs/dGByEj4

### Additional context

Since the particle mods are client side, dedicated server side does not have any mods, just a clean fresh server

the mod ive tested: [Particle Rain](https://modrinth.com/mod/particle-rain), [Explosive Enhancement](https://modrinth.com/mod/explosive-enhancement)

https://github.com/Sinytra/Connector/assets/135343248/94169872-71fc-459d-b47e-47037e85b7d1

**Comment by weegeeluigi** [comment]
Do you have the actual crash report because I see the render thread crash but it doesn't throw the error or stack trace.  I'm curious if it's related to a mixin, similar to my problem [#1004](https://github.com/Sinytra/Connector/issues/1004) since it also is a particle issue with Better Nether blowing up when connected to a server, but the client crashes, but the same world in single player does not.  The mod that causes the crash does have it's own particle system.

**Comment by liangmoe** [comment]
>Do you have the actual crash report

No my game does not crash, everything is fine it just the client side mod not working while playing on server, not sure if this small issue is related to yours or not

**Comment by weegeeluigi** [comment]
I'm not the mod dev I posted because I logged a similar issue and thought you were logging a crash.  It not crashing and not working could be many things, for starters you're using a custom launcher, and you also need to know first thing Su5eD is going to ask that you follow the mod template reporting and eliminate all mods apart from the ones with an issue to eliminate other mods interfering.  Your mod list in your log is extensive.

**Comment by liangmoe** [comment]
?? Im 100% sure im using only sinytra required loader and its dependencies and the particle mods

**Comment by weegeeluigi** [comment]
Unless it's lying and reading cached entries your log file shows mod file lists for various other mods like terrablender, geckolib, etc which leads me to believe you have a bunch of other mods installed.

**Comment by r3xsean** [comment]
> Unless it's lying and reading cached entries your log file shows mod file lists for various other mods like terrablender, geckolib, etc which leads me to believe you have a bunch of other mods installed. Maybe that's default connector extras output for the compats there I honestly have not debugged much since my big giant modpack worked right out of the gate until I placed one single block after a month.

is that not from connector extras? 
![image](https://github.com/Sinytra/Connector/assets/119856819/e0316cab-b9ab-42d4-93db-782bfd23c2d1)
