### ISSUE TITLE
Outdated connector global mod aliases.json

### ISSUE THREAD

**Issue by yoloray** [Sinytra/Connector#1013]
### Mod Name

connector

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/sinytra-connector

### Minecraft version

1.20.1

### Describe the bug

I'm Korean, so I used a translator. Sorry if it's awkward. After the sentence “0 mode conflict warning text” appears, it does not run. > Outdated connector_global_mod_aliases.json configuration file detected. please migrate to the new connector.json configuration

### Steps to reproduce

1.try to apply the Simply skills (fabric) mod.
2.Resolve the errors one by one.
3.When all errors have been resolved, the corresponding message appears. It is assumed to be connector json, so it can no longer be done. The connector is the latest version beta42.
...

### Logs

https://mclo.gs/7Rm6qdN

### Additional context

In the case of the cloth-config mod, there are both a mod that requires forge and a mod that requires fabric, so I installed it with fabric first. I am aware that there may be a problem in this regard, but originally an error log appears asking which forge is required, but it is not currently appearing.

my mod list. 

![모드 리스트](https://github.com/Sinytra/Connector/assets/160310076/a0304109-5f32-45e5-9e63-76dc52cd624b)

**Comment by yoloray** [comment]
I didn't know if it was compat or a bug, so I added the tag as compat, but please tell me if it's wrong.

**Comment by liangmoe** [comment]
Hi, you have duplicated of fabric api, please remove them and install the latest forgified fabric api 
![image](https://github.com/Sinytra/Connector/assets/135343248/ce0af687-7037-41a0-9681-0d72e7df1dab)

>Outdated connector_global_mod_aliases.json configuration file detected. please migrate to the new connector.json configuration

That means you need to migrate `connector_global_mod_aliases.json` into `connector.json`, they are configuration file that located at config folder, the sinytra website explaned those https://sinytra.org/docs/connector/configuration, if you are still dont know what to do you can simply delete both of them and let them regenerated themself, or get help from sinytra discord


At this case the Additional context youve provided will be solved, you can use the forge cloth config because u use the correct global aliases

**Comment by yoloray** [comment]
I realised I was using two when I tried to figure it out on my own, but I was confused, so thanks for the clarification. But I got an error when using forge cloth config. what if it happens afterwards? (log-config2 need)
And I don't know how to migrate... In that case, as you said, Discord and just ask for help?

**Comment by liangmoe** [comment]
Umm, you can simply delete `connector_global_mod_aliases.json` and `connector.json` and let them regenerate them self, they are located at config folder
