### ISSUE TITLE
Things mod crashes on startup

### ISSUE THREAD

**Issue by Xplodin** [Sinytra/Connector#1037]
### Mod Name

Things

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/things-fabric

### Minecraft version

1.20.1

### Describe the bug

crash on boot

### Steps to reproduce

1. Install things mod 0.3.3 + lavender + owolib + trinkets
2. Install connector extras + FFAPI + Connector latest
3. crash via a log only accessible by having the output log open when the game starts
...

### Logs

https://gist.github.com/Xplodin/d9c10ea8ed964bcf1df9a6a37b082209

### Additional context

critical injection failure

**Comment by hiimrickross** [comment]
Can confirm - I removed Mythic Upgrades while troubleshooting something else (resource reload failure after exiting world/in-world) and at the same time removed Things because of your post. Then I tried v43 after fixing the former, thinking that was the reason, and it worked. So I added back Things, forgetting about this post, then it crashed. Removed Things, loaded up back as normal.

Note: Things 3.3 was present on v36->v41 working on Connector, and I believe also v42.
