### ISSUE TITLE
Fabric entities that disable shields don't disable shields

### ISSUE THREAD

**Issue by Shyvvi** [Sinytra/Connector#107]
### Describe the bug

When playing with a fabric mod on forge, entities that are meant to disable the player's shield don't disable their shield.

### Steps to reproduce

1. Take an entity that disables shields from any fabric mod
2. Spawn it in
3. Get a shield
4. Boom

### Additional context

The @Override boolean disablesShield() in the entity's class does not work on forge.

**Comment by Su5eD** [comment]
Can you link a mod that uses this behavior? Or name an entity that is mean to "disable the player's shield"?

**Comment by Shyvvi** [comment]
The mod that was used is actually a mod I am currently working on. On that note I could quickly throw together a mod that creates an entity with this behavior?

**Comment by Su5eD** [comment]
sure, that would be great

**Comment by Su5eD** [comment]
I think this happens due to forge overwriting the method call with its own on `IForgeItemStack` instead.

https://github.com/MinecraftForge/MinecraftForge/blob/ab70bde1d648125acee073a93a25d4b8f08985c9/patches/minecraft/net/minecraft/world/entity/player/Player.java.patch#L124-L125
```diff
    protected void m_6728_(LivingEntity p_36295_) {
       super.m_6728_(p_36295_);
-      if (p_36295_.m_213824_()) {
+      if (p_36295_.m_21205_().canDisableShield(this.f_20935_, this, p_36295_)) {
          this.m_36384_(true);
       }
```

This might actually count as a Forge bug as it also stops the Warden from disabling player shields. I'll open an issue on their repo.

**Comment by Su5eD** [comment]
Looks like it's already been reported
- https://github.com/MinecraftForge/MinecraftForge/issues/8809

**Comment by Shyvvi** [comment]
Oh alright, sounds good! On that note I think it's safe to close this issue.

**Comment by Su5eD** [comment]
Cool. By the time we migrate to neo, the issue should hopefully be fixed on their end.
