### ISSUE TITLE
Eureka / Valkyrian Skies Crashes when using already generated .connector folder

### ISSUE THREAD

**Issue by Matthysse** [Sinytra/Connector#1091]
### Mod Name

Eureka

### Mod Homepage

https://modrinth.com/mod/eureka

### Minecraft version

1.20.1

### Describe the bug

Adding the Eureka/Valkyrian Skies (forge) to the modpack first works, but then doesn't anymore when restarting. The weird thing is, when removing the .connector folder it starts working again. Then when the .connector folder is again regenerated, Minecraft recrashes at startup.

### Steps to reproduce

1. Install the modpack, including Valkyrian Skies/Eureka
2. See the game load normally
3. Reboot the game and see it crash at startup
4. Remove the .connector folder from the mods folder
5. See the game launch again
6. Repeat...

### Logs

https://mclo.gs/UGmKMdL

**Comment by Damiencastro** [comment]
Just wanted to comment that I've experienced the same issues involving mixin for reach_entity_attributes. To add more confusion to the mix, deleting my .connector folder did not allow my game to launch properly. I am running off the following modpack:
"Medieval MC [FORGE] 1.20.1 v26.5 HF." If this issue is not already being worked on, I would be interested in trying to help diagnose the issue. Please let me know if the assistance would be welcome. Thanks!

**Comment by RoomAlex68** [comment]
This issue seems to be Connector Extras 
Refer to https://github.com/Sinytra/ConnectorExtras/issues/33

**Comment by Su5eD** [comment]
> Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Variable modifier target for net/minecraft/client/renderer/GameRenderer::getActualAttackRange1 was removed by another injector [INJECT Applicator Phase -> mixins.reach-entity-attributes.json:client.GameRendererMixin from mod reach_entity_attributes -> Apply Injections ->  -> Inject -> mixins.reach-entity-attributes.json:client.GameRendererMixin from mod reach_entity_attributes->@ModifyVariable::getActualAttackRange1(D)D]

Indeed, this is a CE issue
