### ISSUE TITLE
Incompatiblity with Mending Over Time

### ISSUE THREAD

**Issue by JustNik-jpg** [Sinytra/Connector#1125]
### Mod Name

Mending Over Time

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/mending-over-time

### Minecraft version

1.20.1

### Describe the bug

Game crashes during startup with Mending Over Time installed.

### Steps to reproduce

1. 
2.
3.
...

### Logs

https://gist.github.com/JustNik-jpg/bfa542224b74cade26ca271d3d60d7b7

### Additional context

Tested with only Connector/Forgified Fabric API and Mending Over Time itself installed

**Comment by Su5eD** [comment]
Unfortunately, this cannot be fixed from our side. The issue occurs because of the mod's problematic namespace name, which contains uppercase characters. Fabric seemingly doesn't register the namespace to minecraft's resource manager, likely due to the mod not including any assets. However, Forge registers it regardless of its contents. As this is done by Forge's builtin resource manager, we can't safely guess and remove resources from the mod, as it could have unintended side effects.
