### ISSUE TITLE
Crashed whilst initializing game MC Dungeons Weapons

### ISSUE THREAD

**Issue by Kxrik** [Sinytra/Connector#1132]
### Mod Name

MC Dungeons Weapons

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/mcdw

### Minecraft version

1.20.1

### Describe the bug

Crash on launch

### Steps to reproduce

1. Add to modpack with dependencies listed in the mod page
2. Launch the game
3. Crash

### Logs

https://pastebin.com/DZkznjXf

**Comment by Su5eD** [comment]
> Add to modpack with dependencies listed in the mod page

Please read the issue template more carefully. For modpack related issues, use the `support` channel on our [discord](https://discord.sinytra.org) server.

> Before reporting, please ensure that:
> - You've installed a **minimal set of mods** required to reproduce the issue.
    Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
    Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
    If you're unsure which mods might be at fault, try using binary search - removing half of installed mods
    repeatedly until the faulty mod is found.

This is clearly not the case here as you've got other mods installed as well, namely the Forge version of "Clumps", which is why mcdw is trying to init its compat module for it.

Since the two versions differ in code, Fabric mods built for the Fabric version of Clumps will not work with its Forge build. You can [hide](https://sinytra.org/docs/connector/configuration#hiding-forge-mods-presence) clumps from MCDW to disable this integration.
