### ISSUE TITLE
Bewitchment injection failure

### ISSUE THREAD

**Issue by NoalSimon** [Sinytra/Connector#1164]
### Mod Name

Bewitchment

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/bewitchment

### Minecraft version

1.20.1

### Describe the bug

injector error on start-up

### Steps to reproduce

1. install bewitchment on latest version with correct dependencies
2. crash before game launches with exception error
3. ????
4. Profit?

### Logs

https://gist.github.com/NoalSimon/1c19b6256f7330d6b53acd9592eff2f1

### Additional context

Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method bewitchment$voodooDrownEffect(Lnet/minecraftforge/fluids/FluidType;Lcom/llamalad7/mixinextras/injector/wrapoperation/Operation;)Z in bewitchment.mixins.json:poppet.LivingEntityMixin from mod bewitchment failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap bewitchment-refmap.json

**Comment by NoalSimon** [comment]
I attempted to use the dev build and it still crashed with the same error. unsure of what is causing it

**Comment by kakashi1464** [comment]
Use forge 47.1.3

**Comment by NoalSimon** [comment]
I'd attempted using the earlier forge and it caused like 8 mods to break, I'll try again after adjusting those mods

**Comment by NoalSimon** [comment]
nope same error when downgrading forge to that version and disabling all other mods that conflicted with the downgrade

**Comment by NoalSimon** [comment]
[same error micin inject.txt](https://github.com/user-attachments/files/15856416/same.error.micin.inject.txt)

**Comment by toErIpNid** [comment]
In my experience, Bewitchment seems to crash due to it needing the Trinkets mod from Fabric. When running bewitchment and its required dependencies without it, you get a message saying it needs Trinkets. When you install trinkets, the game either crashes very early, or doesn't even launch before crashing. 

I'm really hoping this gets fixed so I don't have to play fabric just for Bewitchment.

**Comment by RoomAlex68** [comment]
Even if I have trinkets installed as a dependency for Bewitchment. It still crashes when I play on Forge 4.7.30

**Comment by toErIpNid** [comment]
Yes, that's what I said.

**Comment by NoalSimon** [comment]
> In my experience, Bewitchment seems to crash due to it needing the Trinkets mod from Fabric. When running bewitchment and its required dependencies without it, you get a message saying it needs Trinkets. When you install trinkets, the game either crashes very early, or doesn't even launch before crashing.
> 
> I'm really hoping this gets fixed so I don't have to play fabric just for Bewitchment.

trinkets is a required dependency so of course it crashes without it, the issue is not trinkets, it's the voodoo dolls they added in the most recent update that have unsupported player effects for connector. this report is mainly just to bring up this incompat to the devs

**Comment by MrUnicycle** [comment]
> injector error on startup

have you managed to figure anything out? i followed from your post on the bewitchment hub cause I'm having a similar issue. The log doesn't mention the poppets in particular, but it mentions the mixin transmogrifier- I also tried not having trinkets installed, but it was the same deal as what you mentioned experiencing. 



[latest.log](https://github.com/user-attachments/files/16484577/latest.log)

**Comment by NoalSimon** [comment]
> > injector error on startup
> 
> have you managed to figure anything out? i followed from your post on the bewitchment hub cause I'm having a similar issue. The log doesn't mention the poppets in particular, but it mentions the mixin transmogrifier- I also tried not having trinkets installed, but it was the same deal as what you mentioned experiencing.
> 
> [mixin injection error.log](https://github.com/user-attachments/files/16484580/mixin.injection.error.log)

There is nothing to fix, we have to wait for an update to be put out from the connector devs to fix the incompatibility. The bewitchment mod is referencing hooks that don't exist in the compendium of the connector, so it just doesn't work with the latest version. Also I have cyanide mod installed which makes detailed crash reports.

**Comment by hi216** [comment]
im not crashing with bewitchment 2 on the connector ? it work fine with accesories and the compats

**Comment by aking4125** [comment]
The error is 100% caused by not using the recommended forge version for Sinytra which is 47.1.3. 

If you attempt to boot the game with just bewitchment and its required set of other mods on forge version other than 47.1.3 you get the above mixin error (Using Forge 47.3.5). On the OPs lof file they're using 47.3.0:

[connector F470305 bewitchment mixin error.txt](https://github.com/user-attachments/files/16488177/connector.F470305.bewitchment.mixin.error.txt)

Here is the log showing the game successfully boots into the main menu normally with 47.1.3:

[connector F470103 bewitchment boot normal.txt](https://github.com/user-attachments/files/16488185/connector.F470103.bewitchment.boot.normal.txt)


> I'd attempted using the earlier forge and it caused like 8 mods to break, I'll try again after adjusting those mods

That is just the unfortunate side effect of using something like Sinytra. I'm assuming the mod breakage is mods that require a newer version of Forge than what Sinytra recommends. You could either downgrade the mod version to a version of the mod that is fully compatible with 47.1.3 or probably have to deal with the mods not being compatible.

**Comment by MrUnicycle** [comment]
I'm starting to not feel very smart lol. I'm launching the game with just the dependencies and the right forge version, but it still crashes on launch. At this juncture removing bewitchment is gonna be for the best, but I'm just really curious as to what the issue actually is here, so here's a log for my own personal edification. 

[Bewitchment launch crash.log](https://github.com/user-attachments/files/16501768/Bewitchment.launch.crash.log)

**Comment by MrUnicycle** [comment]
Thanks.

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
