### ISSUE TITLE
Eating Animation Mod Compat Textures not working

### ISSUE THREAD

**Issue by Iskaa303** [Sinytra/Connector#1210]
### Mod Name

Eating Animation

### Mod Homepage

https://modrinth.com/mod/eating-animation

### Minecraft version

1.20.1

### Describe the bug

When using eating animation standard mod compat resource pack, modded food has no animation, however when I tried to use it on fabric, mods had animation.

### Steps to reproduce

1. Install Mod
2. Install supported mods (create, farmers delight, etc.)
3. Enable Eating Animation Mod Support Resource pack
4. There are no animations for supported food, only vanilla one

### Logs

.

**Comment by liangmoe** [comment]
The compat for betterend does working

**Comment by Iskaa303** [comment]
Yeah, but it doesn't work with forge mods. Even when I tried it with create mod on forge, or farmers delight forge

**Comment by Su5eD** [comment]
The mod seems to register its eating progress property immediately when it's [initialized](https://github.com/Theoness1/EatingAnimation/blob/8dc8b78b2d7a73fa1895ca1d6bdb0c10eea5aca3/src/main/java/ru/tpsd/eatinganimationmod/EatingAnimationClientMod.java#L19-L20), which happens before any forge mods have registered their items. As a result, these items can't indicate their eating progress ratio. On Fabric, this ends up working due to mods registering their items in the `main` entrypoint that runs before `client`. On Connector, all Fabric entrypoints run before Forge mod ones. It's done this way to match the timing of Fabric. Moreover, FML's entrypoint are executed in parallel, so even if initialized Fabric mods alongside Forge ones, there's no guarantee the order would be correct.

Delaying the property registration should be easy, maybe try asking the mod author if they'd be okay with changing it.
