### ISSUE TITLE
[1.21] Crash on start for ATM10 (0.28) - Neoforge (21.0.163)

### ISSUE THREAD

**Issue by BelleBernice** [Sinytra/Connector#1301]
### Mod Name

Tesseract API / Extended Industrialization

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/extended-industrialization

### Minecraft version

1.21.1

### Describe the bug

It's just a crush with one of the mods, don't know why or how :)

### Steps to reproduce

1. Clean Minecraft instance v1.21 - Neoforge v21.0.163
2. Mods Istalled:
 - [Sinytra Connector](https://www.curseforge.com/minecraft/mc-mods/sinytra-connector)
 - [Forgified Fabric API](https://www.curseforge.com/minecraft/mc-mods/forgified-fabric-api)
 - [Extended Industrialization](https://www.curseforge.com/minecraft/mc-mods/extended-industrialization)
 - [Tesseract API](https://www.curseforge.com/minecraft/mc-mods/tesseract-api-neoforge)
 - [Modern Industrialization](https://www.curseforge.com/minecraft/mc-mods/modern-industrialization)
 - [Cloth Config API](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
3. Crash log: https://mclo.gs/5B9xeZd

### Logs

https://gist.github.com/BelleBernice/94ad0796ac41fbc0ba8156dabcc1e920

### Additional context

I saw a support thread on [Discord ](https://discord.com/channels/1141048834177388746/1271131312115417200) and tested the crash. I started removing some mods and fortunally it was in the first 5 tries. After removing the Tesseract API and Extended Industrialization mods, the client started all fine. Tested it in a clean instance and here we are. Don't know what the problem is, i don't know how to read mods and stuff, just got lucky i guess :)

**Comment by Su5eD** [comment]
Thanks for reporting the issue. I managed to reproduce the crash and tracked it down to Tesseract API's [Mixin Plugin](https://github.com/Swedz/tesseract-neoforge/blob/1.21/src/main/java/net/swedz/tesseract/neoforge/compat/mi/MIMixinPlugin.java), which interacts with MI. The issue itself occurs whenever FFAPI is loaded alongside this mod, as Tesseract loads one of Minecraft's classes too early - e.g. before it can be transformed by Mixin. This causes a crash later as once Mixin has loaded, it cannot transform the class anymore. FFAPI doesn't do anything special here, and I'm confident the mixin plugin would crash with any other mod mixing into the DataProvider class.

Please forward this report to the authors of Tesseract so that they can fix their mixin plugin not to accidentally load unrelated classes. There is nothing we can do about this on our side.
