### ISSUE TITLE
Crash when breaking TNT underwater

### ISSUE THREAD

**Issue by donkeyrat** [Sinytra/Connector#14]
### Describe the bug

When I placed a block of TNT underwater and broke it, the game crashed.

### Steps to reproduce

1. Go to an ocean biome.
2. Place a block of TNT.
3. Break it.
...

### Logs

https://pastebin.com/

### Additional context

Any time block particles are spawned, the game crashes.

**Comment by donkeyrat** [comment]
...breaking any block crashes the game

**Comment by ProbablyNotPetey** [comment]
Breaking any block crashes the game, regardless of mods installed
[crash-2023-08-08_21.43.11-client.txt](https://github.com/Sinytra/Connector/files/12297413/crash-2023-08-08_21.43.11-client.txt)

**Comment by donkeyrat** [comment]
after further analysis, block particles being spawned seems to be the issue; having sheep around kills my game as well

**Comment by quat1024** [comment]
I do *not* crash displaying block particles on Forge 47.1.3 (with `Connector-1.0.0-beta+1.20.1-full` and FFAPI `0.86.1+1.7.2+1.20.1`). Try that.

**Comment by Su5eD** [comment]
Seems to be caused by Forge adding a new [tint hook](https://github.com/MinecraftForge/MinecraftForge/commit/a4bef828366527c93286a7ed7a5a02ebfd6813b2#diff-2c2475fb91e2483e76346183e062f74c8c7c2f64022dbfb9bb531aca29ea8283R8) which removes the call to `BlockState#isOf`, breaking our mixin. NeoForge seems to have applied the commit, too.

Given the current situation around Forge and Neo there's multiple ways we can approach compat in regards to this and possible future issues:
1. Stay on Forge 47.1.3, which seems to be the "stable" version where most people and mainly **mods** are. Ignore future Forge versions for 1.20.1. Update the version ranges on FFAPI and Connector to reject them.
2. Make the problematic mixin optional via a config plugin, falling back to bridging the tint api to forge if the necessary version is present. Downsides: A little too complicated, with possibly more workaround needed should other issues arise.

I'm in favor of 1 here. Let's wait out this weird "transitional period" and continue on Forge 1.20.2 or Neo if it's production-ready by the time.

**Comment by Su5eD** [comment]
Released FFAPI `0.86.1+1.8.1+1.20.1` which no longer crashes on never Forge versions, allowing FML to show the loading error screen with the version range mismatch.
