### ISSUE TITLE
[1.21.1] Crash on dedicated server caused by classloading of client-only class when fabric mod registers a custom fluid.

### ISSUE THREAD

**Issue by Builderb0y** [Sinytra/Connector#1501]
`FluidHandlerCompat.initFabricFluidTypes()` calls into ForgifiedFabricAPI's `FluidRenderHandlerRegistry`, whose implementation loads `WaterRenderHandler`, which has a field of type `TextureAtlasSprite[]`. Since `TextureAtlasSprite` is a client-only class, this crashes on dedicated servers. This issue was reported to me [here](https://github.com/Builderb0y/BigGlobe/issues/58) with [this stack trace](https://github.com/user-attachments/files/17535243/message.txt).

If it's relevant, my fluid registration code can be found [here](https://github.com/Builderb0y/BigGlobe/blob/scriptable-generators/src/main/java/builderb0y/bigglobe/fluids/BigGlobeFluids.java).

**Comment by JR1811** [comment]
Same here on 1.21.1

We are currently on the Modfest event, coding a simple Mod on Fabric to use on NeoForge.
Our mod, [FBombs](https://github.com/Chailotl/fbombs), makes use of a basic fluid. This specifically seemed to let dedicated server environments not boot anymore since its trying to access client only sided code.

## FBombs (Fabric 1.21.1): 
[fluid class](https://github.com/Chailotl/fbombs/blob/master/src/main/java/com/chailotl/fbombs/fluid/JuiceThatMakesYouExplodeFluid.java) | [fluid registration class](https://github.com/Chailotl/fbombs/blob/master/src/main/java/com/chailotl/fbombs/init/FBombsFluids.java)

*In Fabric launches and renders fluid just fine, even on dedicated server environments*

## Server's latest log: 
[latest.log](https://mclo.gs/kkpEWng)

Installed are:
- connector-2.0.0-beta.3+1.21.1-full
- fbombs-1.2.0+1.21
- forgified-fabric-api-0.104.0+2.0.18+1.21.1

**Comment by JR1811** [comment]
Also if im reading the logs right, it has the same issue with...

- net/minecraft/client/gui/screens/**Screen**
- net/minecraft/client/**RecipeBookCategories**
- net/minecraft/client/renderer/**ItemBlockRenderTypes**

... where it's attempting to load those classes on the dedicated Server environment. For us, the error of not being able to boot the server environment, only appeared starting with the new implementation of the basic fluid, tho.

**Comment by Su5eD** [comment]
Fixed in 2.0.0-beta.4+1.21.1
