### ISSUE TITLE
[1.21.1 - 2.0.0-beta.3] AdventureZ no longer works in later versions of NeoForge

### ISSUE THREAD

**Issue by Cixon** [Sinytra/Connector#1527]
### Mod Name

AdventureZ

### Mod Homepage

https://modrinth.com/mod/adventurez

### Minecraft version

1.21.1

### Describe the bug

Worked in older NeoForge `21.1.8` using `adventurez-1.4.21+1.21`

### Steps to reproduce

Install any later NeoForge version, my instance, I used `21.1.72`
Attempt to launch Adventure Z with Connector, see crash below.

### Logs

https://gist.github.com/Cixon/e46163f6b245634756ac8632628a60df

**Comment by lzm11111111** [comment]
I can also reproduce on fabric environment, the client just crash at start up, I think it's because adventureZ doesn't support latest version of fabric api instead of connector issue
[crash-2024-11-13_11.11.45-client.txt](https://github.com/user-attachments/files/17725600/crash-2024-11-13_11.11.45-client.txt)

**Comment by Tapacywka** [comment]
Yeah, it's AdventureZ fault, not the Connector's one.
You need to report this issue to AdventureZ author.

**Comment by lzm11111111** [comment]
https://github.com/Globox1997/AdventureZ/issues/188
