### ISSUE TITLE
Defile / Rattatouie incompatibility

### ISSUE THREAD

**Issue by Thysi2** [Sinytra/Connector#1566]
### Mod Name

Defile / Rattatouie 

### Mod Homepage

https://modrinth.com/mod/defile https://modrinth.com/mod/ratatouille

### Minecraft version

1.20.1 (LTS)

### Describe the bug

Crash on start

### Steps to reproduce

1. Start the game
2. Crash
3. Done
...

### Logs

https://pastebin.com/LgTpbA8R

**Comment by Leopotion3** [comment]
Based on some initial testing i did with the mod yesterday. The library mod **Rattatouie** is not causing the crash as i was able to boot up the game with just it installed.

However when **Defile** is added it crashes the game, and according to logs i recieve, it is due to a mixin that i cant access in the mixins folder of the mod due to it being closed source

Edit: Forgot to type the mixin thats causing the issues, `defile.mixins.json:client.inkling.adapter_generated_ForgeGui`

**Comment by electikos** [comment]
it's the fabric_loader: it's 0.15.3 but it need the 0.16.9 or above
can someone help me to get my hand on it to replace the forgified one ?

**Comment by electikos** [comment]
I have it, how can I replace it to make it work ?

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.

**Comment by BastardNeko** [comment]
Is this seriously abandoned? I can't use fabric since Alex's Caves isn't on it, and getting Defile and Arsenal by doctor4t to work on forge 1.20.1 was the only reason I downloaded this mod, and Alex's Caves and Defile/Arsenal are NOT updated to the newer versions, so upgrading to the latest version for support is not possible. :/ Major Disappointment. Really wish this would be patched.
