### ISSUE TITLE
Error during loading 

### ISSUE THREAD

**Issue by other-seki-arefake** [Sinytra/Connector#17]
### Describe the bug

During the loading the connector mod didn't load correctly

### Steps to reproduce

1- As indicated in the instructions, I downloaded the mod and also the dependencies.
2- Then start minecraft and when loading, the error came out.
![capture](https://github.com/Sinytra/Connector/assets/80777187/98e56f91-4411-4f44-8142-423ed63cc0ff)

### Logs

https://gist.github.com/other-seki-arefake/6177ebeda1fb4c7a128d77cc66798a17

### Additional context

when installing the connector mod, i've add a mod that needed dependencies (NiftyCarts). These were "forge config screen [Fabric]" and "forge config API port [Fabric]"

**Comment by Su5eD** [comment]
Looks to be an incompatibility in Forge config api port, that provides [additional](https://github.com/Fuzss/forgeconfigapiport/blob/8dbbc0d49afb46928a1dfc0c7f828af06da1638d/Common/src/main/java/net/minecraftforge/fml/config/ModConfig.java#L30) constructors for the ModConfig class, which don't exist on Forge. This causes problems when the Forge class is used in Connector rather than what the mod ships.

**Comment by Su5eD** [comment]
Marked `forgeconfigapiport` as incompatible
