### ISSUE TITLE
crash with Bewitchment

### ISSUE THREAD

**Issue by coco875** [Sinytra/Connector#172]
### Mod Name

 Bewitchment

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/bewitchment

### Describe the bug

crash at start

### Steps to reproduce

1. have ffapi, connector and Bewitchment
2. run
3. see

### Logs

https://pastebin.com/np5CdrSb

**Comment by Kitteh6660** [comment]
Even as of latest Connector (beta 15), it still doesn't work.

**Comment by LoSilopante** [comment]
Bewitchment has 3 dependencies: Patchouli, Trinkets, and Pehkui.
A profile with Connector and Pehkui crashes, so I think that one's the incompatibility.

**Comment by LoSilopante** [comment]
[related issue](https://github.com/Sinytra/Connector/issues/328)

**Comment by Zainyest** [comment]
Can confirm, Pehkui Fabric still having issues, but Bewitchment itself is throwing a injection failure with Connector during launch:

https://gist.github.com/Zainyest/5dfd7727073eb8168673c7ac9f38c75e

**Comment by FullMetalMaster** [comment]
Connector beta 32 still same issue

**Comment by SoftySylph** [comment]
Copied from my other post under a different issue since this one seems to be a more popular ticket.

Working initially when used on forge 47.1.3 (Not forge 47.2.X
But crashes upon being turned into a vampire due to the same or a similar mixin, heres a crash log.
[crash-2024-02-25_14.39.15-client.txt](https://github.com/Sinytra/Connector/files/14397575/crash-2024-02-25_14.39.15-client.txt)
mods used:
![image](https://github.com/Sinytra/Connector/assets/92411169/4f966bbf-e475-4de5-9036-6abf2bb157fc)

Edit: 
all newest versions, besides maybe pehkui, but that doesn't come into play here.
soft locks the world since you're stuck in the gui change, also only on the client since its related to gui.
testing is possible using these commands:
/curse add bewitchment:susceptibility
/time set night
/give @s minecraft:totem_of_undying
/give @s bewitchment:vampire_spawn_egg (I think that's the id)

then in survival hold the totem, spawn the vampire and let it kill you, should instantly crash.

Edit 2: Would be nice to have on the newest forge version too though.
