### ISSUE TITLE
EMI loot don't work but the game run

### ISSUE THREAD

**Issue by coco875** [Sinytra/Connector#175]
### Describe the bug

with EMI loot install and EMI (forge version) when I go in EMI loot section don't appears

### Steps to reproduce

1. have connector, ffapi, EMI and EMI loot
2. run
3. go in world and try what mod produce raw salmon

### Logs

[debug.log](https://github.com/Sinytra/Connector/files/12506664/debug.log)

**Comment by Su5eD** [comment]
This is due to how EMI works - it only loads plugins from mods of the same platform. The forge build of the mod does not know about fabric mod entrypoints - which serve as a way to find and invoke plugin classes - and can't load them. I'm planning to introduce a bridge in the future, it's being tracked in
- #189
