### ISSUE TITLE
Integration of Fabric mods with JEI/REI/EMI was broken

### ISSUE THREAD

**Issue by MBYL-InkAndSoul** [Sinytra/Connector#189]
### Describe the bug

You can't use recipe checkers to check machine recipes.

### Steps to reproduce

1. Install Tech Reborn, Modern Industrialization or any other mod that have non-vanilla recipe execution block.
2. Install JEI/REI/EMI and make sure they have integration in Fabric.
3. Check the recipe in game.

### Logs

https://gist.github.com/MBYL-InkAndSoul/97415188ab91e472a57e901000e25c16

### Additional context

Modlist (Forge mods):
- appleskin-forge-mc1.20.1-2.5.0
- architectury-9.1.12-forge
- BetterAdvancements-1.20.1-0.3.2.161
- canary-mc1.20.1-0.2.7
- carryon-forge-1.20.1-2.1.0.1
- cloth-config-11.1.106-forge
- Connector-1.0.0-beta.12+1.20.1-full
- ears-forge-1.19.4-1.4.6
- entityculling-forge-1.6.2-mc1.20
- ForgifiedFabricApi-0.87.0+1.9.8+1.20.1
- ferritecore-6.0.0-forge
- findme-3.1.0-forge
- InventoryProfilesNext-forge-1.20-1.10.7
- ironchest-1.20.1-14.4.4
- kotlinforforge-4.4.0-all
- Ksyxis-Forge1.17-1.1
- LeavesBeGone-v8.0.0-1.20.1-Forge
- libIPN-forge-1.20-4.0.0
- memoryleakfix-forge-1.17+-1.1.2
- modernfix-forge-5.7.2+mc1.20.1
- NaturesCompass-1.20.1-1.11.2-forge
- Patchouli-1.20.1-81-FORGE
- polymorph-forge-0.49.0+1.20.1
- PuzzlesLib-v8.0.24-1.20.1-Forge
- rubidium-extra-0.5.0+mc1.20.1-build.98
- rubidium-mc1.20.1-0.7.0a
- smoothboot-mc1.20.1-0.0.3
- XaerosWorldMap_1.32.0_Forge_1.20

Modlist(Fabric mods):
- Modern-Industrialization-1.7.3
- TechReborn-5.8.7
- tech_enhanced-1.0.3
- RebornCore-5.8.7

Recipe checkers:
- REIPluginCompatibilities-forge-12.0.88
- RoughlyEnoughItems-12.0.652
- RoughlyEnoughProfessions-forge-1.20.1-2.0.1

Or

- jei-1.20.1-forge-15.2.0.27
- emi-1.0.19+1.20.1+forge

**Comment by Su5eD** [comment]
I suspect this happens because recipe viewer mods are designed to only use one platform's plugins as recipe sources, which results in fabric mod integration being ignored. Usually fabric plugins are done using entrypoints, which don't exist on Forge, and therefore the Forge versions of these mods cannot invoke them. The solution for us would be to create a bridge for one of these mods to allow running plugins of other platforms as well. Ideally I'd like to make an EMI addon to run both JEI and REI plugins (from Forge and Fabric) on top of it.
