### ISSUE TITLE
Crash when fabric BetterNetherX mobs present

### ISSUE THREAD

**Issue by Talan67** [Sinytra/Connector#19]
### Describe the bug

Crash on Ticking Entity

### Steps to reproduce

1. Install Connector + Forgified Fabric
2. Install Forge mods
4. Install Better End and Nether mods
3. Create New World
4. Go into Nether
5. Crash

### Logs

https://paste.ee/p/VCV35

### Additional context

Installed Neruina Mod which removes the mobs upon them erroring. Its only the mobs that seems to be causing this. As stated in my previous comment in another post, I'm testing multiple mods. This has been tricky but with a certain mod the game starts up like normal but when loading into a world. The instance freezes up.

Artifacts, Architectury and Oculus crash on start up when loaded up individually. Would ignore these for now though.

**Comment by Talan67** [comment]
Crash when going into the Create Mod Tab in the Creative menu: https://paste.ee/p/wauhq

Cloth Config is causing the World Creation to freeze up, as mentioned in the orignal post.

**Comment by Talan67** [comment]
Caelus API Is the Cause of the Ticking Error

**Comment by Su5eD** [comment]
> Crash when going into the Create Mod Tab in the Creative menu: https://paste.ee/p/wauhq
\>Caused by: java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.objects.Object2IntMap.getInt(Object)" because "this.uniformCache" is null

I am getting the same error without connector installed as well, and I'm sure it's caused by rubidium. Tested this in an instance with:
- Create 0.5.1d
- Rubidium 0.7.0a
- Rubidium Extras 1.4.3

**Comment by Xplodin** [comment]
> Caelus API Is the Cause of the Ticking Error

Ever find a fix to the ticking entity errors?
