### ISSUE TITLE
Styled Player List

### ISSUE THREAD

**Issue by DonorKrovi** [Sinytra/Connector#209]
### Mod Name

styledplayerlist-3.1.1+1.20.1.jar

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/styled-player-list

### Describe the bug

server startup crash

### Steps to reproduce

put and stat sever

### Logs

https://gist.github.com/DonorKrovi/9371c8c91a365266a9d32ca637e8d1d1

**Comment by Su5eD** [comment]
> Caused by: java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/event/EventFactory

This looks like you're missing the Forgified Fabric API. The game can't detect this unsatisfied dependency because the mod doesn't declare it. Please follow the [installation steps](https://github.com/Sinytra/Connector#players) in the readme when installing Connector.

I tested the mod on a local server and it runs fine after installing FFAPI.
![](https://github.com/Sinytra/Connector/assets/51261569/ef9f3a77-01d9-4993-b8d1-d833f5848bcd)
