### ISSUE TITLE
Interface injection of GameProfile fails (with Switchy Proxy)

### ISSUE THREAD

**Issue by sisby-folk** [Sinytra/Connector#214]
### Describe the bug

When running switchy proxy 1.5.7, chat fails because `instanceof SwitchyProxyProfile` (an injected interface) returns false for player gameprofiles.

### Steps to reproduce

1. Inject an interface into GameProfile (this will of course be remap = false) - here's [GameProfileMixin](https://github.com/sisby-folk/switchy-proxy/blob/1.20/src/main/java/folk/sisby/switchy_proxy/mixin/GameProfileMixin.java) from switchy proxy.
2. Test that interface is being implemented by a gameprofile instance using `instanceof` with a logger.
3. Logger returns `false`.

### Logs

https://mclo.gs/tcFdskf

### Additional context

In the log, i'm printing the following:

`SwitchyProxy.LOGGER.info("Interfaces: {} {}", player instanceof SwitchyPlayer, player.getGameProfile() instanceof SwitchyProxyProfile);`

The connector compatible version of styled chat is 2.2.3, which isn't released yet - if this can't be reproduced with a different gameprofile interface injection, let me know and i can provide copies.

**Comment by Su5eD** [comment]
Right, authlib, this is gonna be a bit of a problem. The issue here is that only GAME layer libraries can be mixed into on Forge. I suspect authlib is placed on the BOOT layer, which means mixins targetting its classes will never run. I ran into the same problem in FFAPI, where one of Fabric's mixins was targetting a codec class, and could not be ported over to Forge.

The best solution I can think of would be moving these libraries to the GAME layer, but that is outside of Connector's control. I suppose I could talk to Neo about it though.
