### ISSUE TITLE
SmartBrainLib Fabric

### ISSUE THREAD

**Issue by AzureDoom** [Sinytra/Connector#232]
### Mod Name

SmartBrainLib (Fabric version)

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/smartbrainlib

### Describe the bug

Crashes on Startup

### Steps to reproduce

1. Install just Connector (and it's required custom FAPI) and SmartBrainLib's Fabric version
2. Start game and crash

### Logs

https://gist.github.com/AzureDoom/563b485ce46b223119d46215daf29aa9

### Additional context

The workaround for this is just to use the Forge version of SBL with no issues at least with my mods that use SBL in Fabric.

**Comment by Su5eD** [comment]
For the record, here's the error I got: https://mclo.gs/cYdEklk. It looks like we're not updating the mixin config name inside the fabric.mod.json. Regardless, starting with Connector beta 14, this is no longer an issue since we'll be replacing forge mixin with the fabric fork. That eliminates the need to rename mixin configs to be unique.

I tested SmartBrainLib Fabric on the current dev build and it works fine, so I'll consider this fixed.
