### ISSUE TITLE
Better End Incompat with Distant Horizons 2.0 

### ISSUE THREAD

**Issue by rainysux** [Sinytra/Connector#237]
### Mod Name

Distant Horizons 2.0 (In their server, currently in beta testing, soon to be released) 

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/distant-horizons

### Describe the bug

When Using Connector to bring Better End to forge and using Distant Horizons 2.0, it causes chunks to be unloaded with gaps. While if better end is off, it doesnt happen. 

### Steps to reproduce

1.Download Better End
2.Go to their discord server and download the recent announcements (RC3)  
3.Make a world and will see gaps, if taken off the gaps will be gone and DH will work properly
...
First one is without better end, second is with better end.
![5CB0FE46-3FB5-4A5F-A358-D9A61F7DF3F7](https://github.com/Sinytra/Connector/assets/113203852/fd545967-b2d4-4ff9-9e8f-06cf70fac306)
![FF831547-F23E-4C78-B353-8A1147491B83](https://github.com/Sinytra/Connector/assets/113203852/e0a6fa7f-ff17-4637-b534-8964e55b2a67)

### Logs

Dont have logs however I could do a latest.log if needed

**Comment by AntonyCilleros** [comment]
Didn't see anything weird with the current version of betterend and DH

**Comment by Su5eD** [comment]
Same issue occurs on Fabric with the latest version of BetterEnd and Distant Horizons, and therefore isn't caused by Connector. I recommend reporting it to the mod's developers.

| ![2024-01-12_23 48 33](https://github.com/Sinytra/Connector/assets/51261569/4ed73919-455c-45ff-8ff1-9a2a1392b035) | ![2024-01-12_23 48 49](https://github.com/Sinytra/Connector/assets/51261569/f38f10f5-b2ae-4bd4-8bbe-0374182f1d6e) |
|--------|--------|
