### ISSUE TITLE
The game crashes with FabricSkyboxes

### ISSUE THREAD

**Issue by Lolothepro** [Sinytra/Connector#24]
### Mod Name

FabricSkyboxes

### Mod Homepage

https://modrinth.com/mod/fabricskyboxes

### Describe the bug

Game crashes on startup.

### Logs

https://mclo.gs/o9ETXqY

**Comment by Su5eD** [comment]
This was caused by the fabric sky boxes mod using an invalid url for their website contact. According to fabric's [documentation](https://fabricmc.net/wiki/documentation:fabric_mod_json_spec), it should be a valid URL starting with `http(s)://`.
> - **contact** Defines the contact information for the project. It is an object of the following fields:
>   - **homepage** Project or user homepage. Must be a valid HTTP/HTTPS address.

I added a check to make sure the URL is valid before it is passed into FML, eliminating the crash. However, the mod should also update itself to be compliant with the spec.

Good news is the mod itself works fine:
<img src="https://github.com/Sinytra/Connector/assets/51261569/e5da0a95-8fd9-4a1f-85c3-081ae28a7bf9" width="75%">
