### ISSUE TITLE
[Feature Suggestion] Mod Menu compat

### ISSUE THREAD

**Issue by Abbie5** [Sinytra/Connector#26]
[Mod Menu](https://modrinth.com/mod/modmenu) is the de-facto way to provide mod config screens on Fabric. Forge has an equivalent API, `ConfigScreenHandler`.

To provide better integration for Fabric mods running on Connector/Forge, the Mod Menu [API](https://github.com/TerraformersMC/ModMenu/blob/1.20/src/main/java/com/terraformersmc/modmenu/api/ModMenuApi.java) could be reimplemented in Connector (or FFAPI?).

For reference, another project has already reimplemented the Mod Menu API for a different purpose: [Menulogue](https://github.com/MrCrayfish/Menulogue)

**Comment by Su5eD** [comment]
Sounds like a good idea. I'd make it a separate project as part of Sinytra to bridge the mod menu api to Forge. Should be doable given that there is already a similar project implementing their api.

**Comment by Su5eD** [comment]
Turns out it's actually just 2 classes so I've built it into connector by default. This is how it looks like in-game.

| ![](https://github.com/Sinytra/Connector/assets/51261569/f9ab8a33-2b67-47ba-b644-1a45f625cf6e) | ![](https://github.com/Sinytra/Connector/assets/51261569/408d46f2-10a5-477c-a948-06d0a8257a4c) |
|--------|--------|

**Comment by Abbie5** [comment]
Thanks!
