### ISSUE TITLE
MiniHUD doesn't display any info lines

### ISSUE THREAD

**Issue by StarskyXIII** [Sinytra/Connector#274]
### Mod Name

MiniHUD

### Mod Homepage

https://legacy.curseforge.com/minecraft/mc-mods/minihud

### Describe the bug

Doesn't display any info lines ingame.

### Steps to reproduce

1.Install following mods
- Sinytra Connector: [Latest Build](https://github.com/Sinytra/Connector/actions/runs/6224691147)
- Connector Extras: v1.1.0
- Forgified Fabric API: v0.88.1+1.9.11
- MaLiLib: [v0.16.2](https://legacy.curseforge.com/minecraft/mc-mods/malilib/download/4723020)
- MiniHUD: [v0.27.0](https://legacy.curseforge.com/minecraft/mc-mods/minihud/download/4593082)

2. Launch Game

3. Create & Enter the world

4. See top left of the screen, and there is no info line.
...

### Logs

https://mclo.gs/mrzJA5B

**Comment by Fiz-Victor** [comment]
press h?

**Comment by StarskyXIII** [comment]
![2023-09-19_01 46 39](https://github.com/Sinytra/Connector/assets/71606873/9e221047-2903-40a5-84d6-634cda4619f5)
![2023-09-19_01 46 50](https://github.com/Sinytra/Connector/assets/71606873/491e4e0e-9041-4f4d-b41d-4ef6f2c66362)

**Comment by leyxcx** [comment]
just butting in to say that minihud has an unofficial port; just in case that helps at all because a port is probably better

https://modrinth.com/mod/bocchud
https://modrinth.com/mod/mafglib

**Comment by StarskyXIII** [comment]
Some features of Forge port will crash game
Such like: mainRenderingToggle, OverlayStructureMainToggle

**Comment by Su5eD** [comment]
The good news is the hud renderer has been patch, so you can now see the minihud info rendered properly.
However, there is a second, worse issue: Malilib class `BaseTextFieldWidget` contains a [`setCursorPosition(int)`](https://github.com/maruohon/malilib/blob/1c29328b563657c7c9c25b9aaa8a121785d4168b/src/main/java/malilib/gui/widget/BaseTextFieldWidget.java#L526) method that comes from malilib, not vanilla. However, if we remap the mod to use mojmap instead of yarn, this method now becomes inherited from `EditBox.setCursorPosition`. As a result, `setCursorPosition` and `moveCursorTo` become cycled and throw a `StackOverflowException` when the uses scrolls the config menu.
