### ISSUE TITLE
Alex Caves biomes do not generate with Biolith

### ISSUE THREAD

**Issue by enzogfaria** [Sinytra/Connector#396]
### Describe the bug

Alex Caves biomes do not generate with Biolith

### Steps to reproduce

1. put the alexcaves mod together with biolith
2. enter a world
3. do the command /locate biome #alexscaves:alexs_caves_biomes
...

### Additional context

![Screenshot_104](https://github.com/Sinytra/Connector/assets/123766918/000be504-4b02-4372-829f-f6397d0b39f8)

**Comment by DonorKrovi** [comment]
maybe this Biolith issue?

**Comment by enzogfaria** [comment]
Maybe, but since a similar problem occurred before, I was told to open an issue

**Comment by geesl** [comment]
Did you try teleporting yourself 10000+ blocks away and testing again? In my case, the caves are just that far apart.

**Comment by enzogfaria** [comment]
Yes, I tried that but it didn't work, it turns out that if I enter the world without it it loads normally, when I put it on it doesn't load

**Comment by rainysux** [comment]
which mod uses biolith?

**Comment by enzogfaria** [comment]
terrestria, cinderscape and promenade

**Comment by Su5eD** [comment]
I don't know which method Alex's Caves uses to generate biomes, but looking at their issue tracker there's a bunch of forge mods, too, that are causing problems with biome gen. I'll investigate nevertheless

**Comment by enzogfaria** [comment]
okay

**Comment by Su5eD** [comment]
Here are my findings:

- Biolith is deliberately configured to always [inject last](https://github.com/TerraformersMC/Biolith/blob/078706fe496f611e8492204c2d29001148160525/src/main/java/com/terraformersmc/biolith/impl/mixin/MixinMultiNoiseBiomeSource.java#L28) to ensure compatibility with terrablender.
- Terrablender's [mixin](https://github.com/Glitchfiend/TerraBlender/blob/a3fd3a82f0cb3b5a4da724e00e8e0783f7e78bf9/Common/src/main/java/terrablender/mixin/MixinMultiNoiseBiomeSource.java#L31) uses default priority, which means "lottery" decides who comes out on top.
- Citadel's [mixin](https://github.com/AlexModGuy/Citadel/blob/718086e6fdbe9dca33e69dbbccde1b336d291965/src/main/java/com/github/alexthe666/citadel/mixin/MultiNoiseBiomeSourceMixin.java#L21) also uses default priority, but only cancels conditionally.

Terrablender always cancels, just like biolith, so it's enough that this race condition ends in terrablender injecting last, and alex's caves will never be able to run its replacements.
I don't know how SortedSet decides the order of equal elements, it could be the hashcode, name, anything.
But right now, terrablender goes first, and so AC has a change to run its replacements where needed

### The solution

Since citadel only cancels where neded, it's enough that the mixin priority be lowered below biolith's one, and it should be guaranteed to work. As I found out it is technically unrelated to connector, I'll pass it onto alex, and then close this issue.

**Comment by Su5eD** [comment]
Superceded by https://github.com/AlexModGuy/Citadel/issues/136
