### ISSUE TITLE
Axiom incompatibility with Embeddium

### ISSUE THREAD

**Issue by PixusPanic** [Sinytra/Connector#399]
### Mod Name

Axiom (1.5.1), Embeddium

### Mod Homepage

https://modrinth.com/mod/axiom https://modrinth.com/mod/embeddium

### Describe the bug

When both Axiom and Embeddium are ran together, the game crashes upon booting.

### Steps to reproduce

1. Install both Axiom and Embeddium.
2. Run the game.
3. The game crashes upon booting.

### Logs

https://gist.github.com/PixusPanic/f9d210b2626d2ff9bd7d4ea5682e4d8c

### Additional context

Without Embeddium, Axiom seems to work perfectly fine, other than a few missing graphics here and there (such as the context menu when you press left alt by default). I suspect that it has to do with Sodium not properly being "registered" for a mixin since it mentions "axiom.mixins.json:render.MixinLevelRendererWithoutSodium" in the crash log. I haven't tried using Sodium in the mod list yet but I thought Embeddium would work cleaner than it since it's made more as a intended port of it for Forge, but I could be wrong.

I also have to thank you for making this amazing mod and bridging a lot of the gap between mod loaders, especially as someone who just wants to build.

**Comment by Su5eD** [comment]
Hi, thanks for reporting the issue. I've fixed context rendering once before but it seems like it broke again, sorry about that. 

Guessing by the name of the `MixinLevelRendererWithoutSodium` class, axiom likely applies different mixins based on whether sodium is present or not. So in theory, aliasing embeddium to be also listed as `sodium` should do the trick. I'll likely have to add a global mod aliasing system to make this work with modpacks, and so that users don't have to edit mod jars themselves.

**Comment by Su5eD** [comment]
Looks like it works fine with embeddium. I had to edit the embeddium jar manually to add `provides=["sodium"]`, and then add a dependency override for axiom to remove a `breaks` rule, since sodium and embeddium follow diffrent versioning.

For the global alias system, I'd go with a simple JSON file similar to fabric dependency overrides, with aliases listed as arrays for each modid:
```json
{
    "foo": "example",
    "bar": ["lorem", "ipsum"]
}
```

![](https://github.com/Sinytra/Connector/assets/51261569/3df11e63-f9b4-4443-9585-0073e5f2c1e4)

**Comment by Su5eD** [comment]
There we go. You should now be able to get it running smoothly with the next release (or latest dev build), provided that you create an alias for embeddium and remove the breaking dependency constraint from axiom. Here's my config files that I've used, both are located inside the config folder:

`connector_global_mod_aliases.json`
```json
{
  "version": 1,
  "aliases": {
    "cloth_config": "cloth-config2",
    "embeddium": "sodium"
  }
}
```

`fabric_loader_dependencies.json`
```java
{
  "version": 1,
  "overrides": {
    "axiom": {
      "-breaks": {
        "sodium": "NONE"
      }
    }
  }
}

```

**Comment by KubFire** [comment]
Hi, I am kinda a newbie, so to fix axiom from crashing, i gotta create two JSONs with what you have written inside, put them into .minecraft/config and run the game again? Cuz for me its stil crashing:/

**Comment by vinnyg0621** [comment]
it's still crashing for me too, please help!
