### ISSUE TITLE
Crash when both AE2 (forge) and Modern Industrialization (fabric) are loaded

### ISSUE THREAD

**Issue by Gronglegrowth** [Sinytra/Connector#404]
### Describe the bug

When both AE2 and MI are loaded together, it results in a crash on launch.

### Steps to reproduce

1. Install Sinytra Connector 1.0.0-beta19
2. Install AE2 15.0.3, MI 1.7.4, and their dependencies
3. Attempt to start up the game
4. Observe a crash

### Logs

https://mclo.gs/aneOzSW

**Comment by Su5eD** [comment]
I fixed a conflict with AE2's early registration, though MI will still initialize its addon items without registering them. This is due to AE2 not running its addon entrypoint on Forge. It's also not possible to run a bridge like we do with other mods because AE2 for Fabric and Forge are two independent versions.

Fortunately, MI provides a config option to disable AE2 integration entirely. This comes in handy when you're running the Forge version of AE2, which is not supported by the integration. To do so, open the `modern_industrialization.toml` config file and set `enableAe2Integration` to `false`. AE2 and MI will then run fine.
