### ISSUE TITLE
Traverse and Terrestria are broke in Connector beta4.

### ISSUE THREAD

**Issue by Wudji** [Sinytra/Connector#44]
### Mod Name

Traverse and Terrestria

### Mod Homepage

https://modrinth.com/mod/traverse

### Describe the bug

Traverse and Terrestria break in Connecrot beta4. However they worked perfectly in beta3.

### Steps to reproduce

1.Install Traverse, Terrestria, Connector and other mods
2.Start game
3.The game reported "JAR TRANSFORMATION ERROR".

### Logs

https://mclo.gs/SpNS8pU

**Comment by Wudji** [comment]
It looks like some of the mods that originally worked in beta3 are not working properly in beta4， for example the durability viewer, Traverse and Terrestria

**Comment by Su5eD** [comment]
The issue happened because I rewrote the refmap remap code and relied on the assumption that all refmap files exist, except that's not always the case. Such an example is terrestria worldgen, which lists a refmap in its mixin config but doesn't actually contain one. This is now fixed in 21856352e9ce0acf2a493125d6395d21e00701e0 and will be shipped in the next release.
