### ISSUE TITLE
Beta 21 fails to transform Andromeda.

### ISSUE THREAD

**Issue by melontini** [Sinytra/Connector#460]
### Describe the bug

Same as title.

### Steps to reproduce

1. Install latest Andromeda
2. Crash due to `java.lang.ArrayIndexOutOfBoundsException`.

### Logs

https://mclo.gs/vc1CgdQ

### Additional context

There's an additional crash due to `dev.su5ed.sinytra.connector.mod.compat.fieldtypes.RedirectingIdMapper overrides final method net.minecraft.core.IdMapper.m_7942_(I)Ljava/lang/Object;` (Do ATs apply if a transformer crashes?)
Log: https://mclo.gs/r93mmKr

**Comment by Su5eD** [comment]
> Do ATs apply if a transformer crashes

This happens due to Forge not applying ATs and JS coremods in invalid loading states, which are triggered by missing deps or early loading exceptions, yet Mixins still apply. I've fixed the crash in beta 22 (dev) by moving the `RedirectingIdMapper` initializer to another class, so that java won't try to resolve it unless the method is called. However, other mods might still cause similar crashes as they don't account for such cases.
