### ISSUE TITLE
Regions Unexplored / Terrestria issues

### ISSUE THREAD

**Issue by Brcyden** [Sinytra/Connector#463]
### Mod Name

Regions Unexplored

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/regions-unexplored

### Describe the bug

Terrestria only works with regionsunexplored if you use the fabric version of regionsunexplroed and fabric terrablender. With these two fabric mods. Bosses of mass destruction doesnt work. You have to choose between terrestria or BOMD.

### Steps to reproduce

1. Install terrablender, BOMD, regionsunexplored, and terrestria
2. Run game
3. Crash
...

### Logs

https://pastebin.com/pFyRHJra

**Comment by RoomAlex68** [comment]
And Traverse

**Comment by Su5eD** [comment]
> Terrestria only works with regionsunexplored if you use the fabric version of regionsunexplroed and fabric terrablender

Do you have Connector Extras installed? It adds a bridge between Forge Terrablender and Fabric mods that use it, which usually eliminated this problem

**Comment by Brcyden** [comment]
Yes I do

**Comment by RoomAlex68** [comment]
I used fabric version of Terrablender but crashes still when terrestria and traverse are present with regions unexplored fabric and biome makeover fabric

**Comment by Su5eD** [comment]
This issue is the results of a mixin conflict between one of terrestria's libraries and regions unexplored. The reason RU for fabric works fine is because they patched their mixin to work with terrestria on fabric. However, the same change hasn't been applied to RU Forge.

The solution is quite simple - `EatBlockGoalMixin`'s priority must be lowered below 1000. The fabric version uses priority `999`.

**Comment by RoomAlex68** [comment]
Oh by the way I used forge version of terrablender because I had Biomes O Plenty installed
