### ISSUE TITLE
Biolith incompatible with Dungeons Content mod

### ISSUE THREAD

**Issue by rainysux** [Sinytra/Connector#472]
### Mod Name

Dungeons Content

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/minecraft-dungeons-content

### Describe the bug

Loads a world forever

### Steps to reproduce

1.Have dawn api/promenade since it comes with biolith
2.Add dungeons content 
3.World no matter if its new or pregeneerated it will take forever to load
...

### Logs

https://pastebin.com/ratPnGGB

**Comment by Su5eD** [comment]
This seems like an unfortunate conflict between the two mods. The crash / freeze happens due to an exception that is thrown during world load:
> Exception caught during firing event: Cannot invoke "net.minecraft.core.Holder.m_203565_(net.minecraft.resources.ResourceKey)" because the return value of "net.minecraft.world.level.biome.MultiNoiseBiomeSource.biolith$getDimensionType()" is null

The `biolith$getDimensionType` method returns the value of the `biolith$dimensionTypeEntry` field, which is set by [biolith](https://github.com/TerraformersMC/Biolith/blob/master/src/main/java/com/terraformersmc/biolith/impl/mixin/MixinDimensionOptions.java) in the constructor of `MixinDimensionOptions`.

What Dungeons Content does is that it modifies the existing `MultiNoiseBiomeSource` instance and replaces it with its own wrapper. The new instance never has its `biolith$dimensionTypeEntry` field set by biolith, as the dimension options have already been created for the respective dimension and set for the previous instance.

Connector can't fix this as it's a conflict between the two mods, but I can recommend a solution to devs:
- Preferably, Dungeons Content should look into a better way of injecting its worldgen content, either via apis, existing library mods or (not recommended) mixins.
- Alternatively, Biolith could look into alternative ways of setting / retrieving dimension options for a given `MultiNoiseBiomeSource` instance to account for cases where it gets replaced.
