### ISSUE TITLE
Incompatibility with Cloth Config

### ISSUE THREAD

**Issue by ChiefLogan3010** [Sinytra/Connector#493]
### Mod Name

Cloth Config

### Mod Homepage

https://legacy.curseforge.com/minecraft/mc-mods/cloth-config

### Describe the bug

The game crashes on launch with Cloth Config & Sinytra Connector

### Steps to reproduce

1. Download Sinytra Connector, Forgified Fabric API and Cloth Config API
2. Launch the game
3. Crash
...

### Logs

https://gist.github.com/ChiefLogan3010/b308bbb433f4bc8d4876d72cea1e4978

### Additional context

Mod versions used:
Forge 47.1.3
Connector-1.0.0-beta.23+1.20.1
fabric-api-0.90.7+1.9.30+1.20.1
cloth-config-11.1.106-forge

I imagine a lot of the other mods labelled as incompatible are actually an issue with Cloth Config rather than those mods, as many mods depend on it and I've seen it in many incompatibilities listed here.

**Comment by DoritosSpR** [comment]
try using connector extras

**Comment by ChiefLogan3010** [comment]
I get the same crash when adding Connector Extras

**Comment by Su5eD** [comment]
> at com.tterrag.blur.Blur.<clinit>(Blur.java:23) ~[cloth-config-11.1.106-forge.jar%23164!/:?]

Your log says you have Blur installed, but you haven't included it in the issue description. Why? Does it occur without it installed? Still, please provide a crash log with only the listed mods installed in your instance.  
It also says blur originates from the cloth config forge jar for some reason, which seems weird. Please list all jars in your mods directory.

> Caused by: java.lang.NoClassDefFoundError: me/shedaniel/autoconfig/ConfigData

The ConfigData class is common for both fabric and forge versions of cloth config, so I don't think this happens due to the forge version being used. Can you please upload your debug log and verify your cloth-config jar is not corrupt?

**Comment by ChiefLogan3010** [comment]
That's very odd, I'd disabled Blur (along with all other mods except those listed above) as part of a binary search to find out what was causing the crash. After deleting and reinstalling Cloth Config it seems to be working, so this must have been some kind of corrupt jar like you say.

**Comment by Su5eD** [comment]
Okay, let me know if it happens again.
