### ISSUE TITLE
Chests added by Fabric mods don't animate with Fresh Animations Extensions.

### ISSUE THREAD

**Issue by Wanderer70** [Sinytra/Connector#495]
### Mod Name

Example: Better Nether & Fresh Animations Extentions

### Mod Homepage

https://www.curseforge.com/minecraft/texture-packs/fresh-animations-extensions/files?page=1&pageSize=20

### Describe the bug

By default, with Fresh animations Extensions vanilla chests as well as modded chests have an opening/closing animation. The same thing cannot be said about Fabric mods though. For example, Better Nether's chests behave like normal chests.

### Steps to reproduce

1. Install Connector and it's dependencies/addons
2. Download Fresh Animations AND Fresh Animations Extensions
3. Enable them in resource packs and compare

### Logs

Not a crash

### Additional context

**VANILLA CHEST**
![2023-11-10_14 19 01](https://github.com/Sinytra/Connector/assets/97387920/54189946-a796-4104-a30f-6462de205a20)

**AETHER CHEST**
![2023-11-10_14 19 25](https://github.com/Sinytra/Connector/assets/97387920/f98d1cbc-ff4f-4c83-b12e-d4e13073e9f5)

**BETTER NETHER CHEST** (NOT ANIMATED)
![2023-11-10_14 19 36](https://github.com/Sinytra/Connector/assets/97387920/ad084ffd-e737-4494-a7be-75b9e1286c7f)

As someone who knows nothing about modding, I suspect it has to do something with how blocks are registered/handled.

**Comment by Su5eD** [comment]
Are you using embeddium / rubidium / optifine alongside the texture pack?

**Comment by Su5eD** [comment]
I've tried this out using the Entity Model Features mod for enabling optifine's CEM, and I believe I figured out what's wrong. I've installed the [Iron Chests](https://legacy.curseforge.com/minecraft/mc-mods/iron-chests) Forge mod to see if this only affects fabric mods, but chests from that mod weren't animated either.

After looking at the Aether's and Iron Chests' code, I learned that the animation depends on what model the chest uses. Internally, Aether's chest uses the [vanilla chest model](https://github.com/The-Aether-Team/The-Aether/blob/0a3dbfe34318b7568ed88bfb8d63bfd951023e06/src/main/java/com/aetherteam/aether/client/renderer/blockentity/TreasureChestRenderer.java) with its own texture applied to it. However, the other two mods - Better Nether and Iron Chests - use their own models for rendering. ([\[1\]](https://github.com/paulevsGitch/BCLib/blob/main/src/main/java/ru/bclib/client/models/BaseChestBlockModel.java), [\[2\]](https://github.com/progwml6/ironchest/blob/842f134e487c18b7a619e7694665d8a612d92c44/src/main/java/com/progwml6/ironchest/client/render/IronChestRenderer.java)).

Because the texture pack modifies the vanilla chest model, only mods using it will be animated, regardless of which modloader they're made for.

**Comment by Wanderer70** [comment]
Oh, I see! Sorry for the trouble :D
Yeah I was using ETF, EMF
