### ISSUE TITLE
Incompat with BlossomPvp in server

### ISSUE THREAD

**Issue by rainysux** [Sinytra/Connector#508]
### Describe the bug

Crashes on Server

### Steps to reproduce

https://pastebin.com/NkeZTXae
It crashes in server side, I have not tried client

**Comment by Su5eD** [comment]
BlossomPvp tries to create their own logger with the `SysOut` appender. However, in FML's log4j config, this appender is called `Console` instead. Not being able to find it leads to the crash. I tried aliasing the console logger to SysOut, but that wouldn't work due to BloosomLib reloading the log4j config at runtime, removing all my changes.

Thankfully, the mod's config contains an option to disable this behavior and avoid crashing the game.  
In `config/BlossomMods/BlossomLib.json`, set
```json
"logging": {
    "disableCustomLogger": false
}
```
