### ISSUE TITLE
Terrestria still doesn't work 1.20.1

### ISSUE THREAD

**Issue by Darienn22** [Sinytra/Connector#552]
### Mod Name

Terrestria

### Mod Homepage

modrinth.com/mod/terrestria

### Describe the bug

Terrestria used to have a yellow triangle with an exclamation point on the Mod Compatibility page for Sinytra Connector. Now it has a green checkmark, so I decided to try and play with Terrestria again. When I started the game, it crashed with the same error messages I had before.

### Steps to reproduce

1. Add Terrestria version 1.20.1 to mods folder.
2. Press Play.
3. Game crashes.
...

### Logs

https://hastebin.com/share/anolokumis.vbnet

### Additional context

Please help!

**Comment by Su5eD** [comment]
This appears to be the same issue as #463, a mixin conflict between terrestria and regions unexplored. See the full explanation [here](https://github.com/Sinytra/Connector/issues/463#issuecomment-1789236922).

> The reason RU for fabric works fine is because they patched their mixin to work with terrestria on fabric. However, the same change hasn't been applied to RU Forge.
The solution is quite simple - `EatBlockGoalMixin`'s priority must be lowered below 1000. The fabric version uses priority `999`.

I recommend reporting this to the devs so that the issue can be fixed properly.

**Comment by KirboSoftware** [comment]
We (from regions unexplored) are aware of this issue 👍 We will fix this asap
