### ISSUE TITLE
Breaks with indium and rubidium 

### ISSUE THREAD

**Issue by kakashi1464** [Sinytra/Connector#59]
### Describe the bug

Minecraft crashes when Connector beta4-5 with indium and rubidium

### Steps to reproduce

1.Add Connector beta 4-5 with indium and rubidium in mods folder
2.Run Minecraft

### Logs

https://mclo.gs/f10pAI2 - latest log
https://mclo.gs/zb3BiKl - crash-report
https://mclo.gs/2ck1XBz -debug log

### Additional context

Everything works with connector beta3

**Comment by Su5eD** [comment]
It probably isn't, but this issue specifically happens to be an adapter transformer bug in LVT offsets.

**Comment by Su5eD** [comment]
I was able to fix the LVT patch, and no other issues popped up. When running Rubidium with Indium, the glass issue described in #56 disappeared, too. However, while everything might appear to work at first glance, keep in mind you're actually running a pure Fabric Rendering API implementation (indium) that is not bridged to forge and does not support its render types. This might break both fabric and forge mods that rely on rendering.

**Comment by Su5eD** [comment]
One last thing - starting with the next release, Connector will evaluate fabric mod dependencies before loading mods. As indium requires `sodium` by default and rubidium's modid is different, you will need to override this dependency in order to run indium.

Fabric has a useful workaround called [dependency overrides](https://fabricmc.net/wiki/tutorial:dependency_overrides) you can use for this. It's supported in Connector, too.  
Here's my `fabric_loader_dependencies.json` I used:
```json
{
  "version": 1,
  "overrides": {
    "indium": {
      "-depends": {
        "sodium": "IGNORED"
      }
    }
  }
}
```

**Comment by Lolothepro** [comment]
> I was able to fix the LVT patch, and no other issues popped up. When running Rubidium with Indium, the glass issue described in #56 disappeared, too. However, while everything might appear to work at first glance, keep in mind you're actually running a pure Fabric Rendering API implementation (indium) that is not bridged to forge and does not support its render types. This might break both fabric and forge mods that rely on rendering.

I can confirm that it doesn't work perfectly, as some mods using FAPI are broken with Rubidium + Indium.
