### ISSUE TITLE
Startup crash with Spectrum

### ISSUE THREAD

**Issue by unilock** [Sinytra/Connector#592]
### Mod Name

Spectrum

### Mod Homepage

https://github.com/DaFuqs/Spectrum

### Describe the bug

The game crashes on startup with Spectrum present.

### Steps to reproduce

1. Install Forge, Connector, Spectrum, dependencies
2. Start the game
3. Crash

### Logs

https://gist.github.com/unilock/efba52db192ab6e6e4bb258f92dfc2fb

### Additional context

Spectrum declares a dependency on Fabric API 0.91.0, while Forgified Fabric API only provides up to 0.90.7.  
[`fabric_loader_dependencies.json`](https://fabricmc.net/wiki/tutorial:dependency_overrides) can be used to override this:

```json
{
  "version": 1,
  "overrides": {
    "spectrum": {
      "depends": {
        "fabric-api": ">=0.90.7"
      }
    }
  }
}
```
(EDIT: the next version of Spectrum (1.7.3?) should have this dependency issue fixed)

The error as reported in the linked `debug.log`:
```
[07Dec2023 16:23:38.497] [main/ERROR] [mixin/]: Critical injection failure: LVT in net/minecraftforge/client/gui/overlay/ForgeGui::renderArmor(Lnet/minecraft/client/gui/GuiGraphics;II)V has incompatible changes at opcode 30 in callback spectrum.mixins.json:client.adapter_generated_ForgeGui from mod spectrum->@Inject::spectrum$renderHealthBar(Lnet/minecraft/client/gui/GuiGraphics;IILorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Lnet/minecraft/world/entity/player/Player;IZJILnet/minecraft/world/food/FoodData;IIIIFIIII)V.
 Expected: [Lnet/minecraft/world/entity/player/Player;, I, Z, J, I, Lnet/minecraft/world/food/FoodData;, I, I, I, I, F, I, I, I, I]
    Found: [I, I]
Available: [I, I]
```

**Comment by Fiibii853** [comment]
With the latest version of Spectrum and Connector I am getting a mixin injection error:

`Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector spectrum$updateMovementInFluid(Lnet/minecraft/world/level/material/FluidState;Lnet/minecraft/tags/TagKey;)Z in spectrum.mixins.json:EntityApplyFluidsMixin from mod spectrum failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap spectrum-1.7.4-deeper-down-refmap.json`

Console Output:
https://gist.github.com/Fiibii853/1356ffe41125996c55724f58d4d35a84

Debug Log:
https://gist.github.com/Fiibii853/262be52c8c835ae7cbfeb5a276557450

**Comment by unilock** [comment]
This has likely been fixed on Spectrum's end with the merging of https://github.com/DaFuqs/Spectrum/pull/308. A new version of Spectrum containing this PR has yet to be released.

**Comment by charliez0** [comment]
> This has likely been fixed on Spectrum's end with the merging of [DaFuqs/Spectrum#308](https://github.com/DaFuqs/Spectrum/pull/308). A new version of Spectrum containing this PR has yet to be released.

I have tested the git version and still not been able to start the game. Another error occurs but seems not be connector's issue.

**Comment by Fiibii853** [comment]
I tested with the latest git version, still works on fabric but getting a new error with connector on forge:
`Caused by: java.lang.IllegalStateException: Missing layer definitions: [spectrum:preservation_turret_head#main, spectrum:monstrosity_head#main, spectrum:kindling#main, spectrum:monstrosity#main, spectrum:warden_head#main, spectrum:lizard#horns, spectrum:eraser#body, spectrum:kindling_head#main, spectrum:egg_laying_wooly_pig#wool, spectrum:lizard#frills, spectrum:egg_laying_wooly_pig#main, spectrum:egg_laying_wooly_pig_head#main, spectrum:kindling_armor#main, spectrum:kindling_cough#main, spectrum:eraser_head#body, spectrum:kindling_saddle#main, spectrum:bedrock_armor#main, spectrum:bedrock_armor#feet, spectrum:lizard_head#main, spectrum:lizard#main, spectrum:preservation_turret#main, spectrum:egg_laying_wooly_pig#hat]
`

Crash Report:
https://gist.github.com/Fiibii853/f0d34bbf60ecf2286d6b6bbd4e5f9874

Debug Log:
https://gist.github.com/Fiibii853/b60d1990651e951f51c6c0768bb897a4

**Comment by Tomat777** [comment]
![image](https://github.com/Sinytra/Connector/assets/146892171/669335dc-d848-4df5-b926-819570a36d75)
its good

**Comment by charliez0** [comment]
> ![image](https://private-user-images.githubusercontent.com/146892171/298884178-669335dc-d848-4df5-b926-819570a36d75.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMDU2MDksIm5iZiI6MTcwNjAwNTMwOSwicGF0aCI6Ii8xNDY4OTIxNzEvMjk4ODg0MTc4LTY2OTMzNWRjLWQ4NDgtNGRmNS1iOTI2LTgxOTU3MGEzNmQ3NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyM1QxMDIxNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYzhlZWY4NjQ3ODlmNzg2Mjc5ZmViMWYxZjVjMjc2N2VmY2I3YWI4MGFkMjU4YTQ3MzgwNDRmYzIyMjJmODdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.D077iEaGDZX75aKl6J0pNYyrjYSKwj2HdxDkJCsPoJU) its good

can you post your mods list?

**Comment by Fiibii853** [comment]
> Do u use fixed version of revelation?

I wasn't aware of this, can confirm that everything works properly with https://github.com/DaFuqs/Revelationary/pull/11
