### ISSUE TITLE
Beta 30 breaks hybrid aquatic

### ISSUE THREAD

**Issue by Tomat777** [Sinytra/Connector#619]
### Mod Name

hybrid aquatic

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/hybrid-aquatic

### Describe the bug

FissingBobberEntityMixin Error transforming jar

### Steps to reproduce

Install mod. Launch minecraft.

### Logs

Log https://gist.github.com/Tomat777/4fd0166e662a4f4c1b7aea7435c00006

### Additional context

Debug https://gist.github.com/Tomat777/56682677a5bc762d0214de5d80eb6db9
![image](https://github.com/Sinytra/Connector/assets/146892171/c41e6b96-efac-4ed0-af94-fed814345a6c)
![image](https://github.com/Sinytra/Connector/assets/146892171/7b833300-f6d1-4097-ac47-e55f101a85f9)
Beta 29 works fine

**Comment by Groupix05** [comment]
Hybrid aquatic still doesnt work properly for me.
I still have the Error transforming jar
I need to start my game 2 Times, and on server im unable to start it.
On client ,when I launch the game for the first Time ,my game crash but hybridaquatic is transformed successfully ,that's why I Can start a second Time my game and everything works

I really love this mod but im unable to start my server with it 

(Im on phone rn so I cant put logs, but you can try Yourself with my modpack ColoCraft - modern Adventures VeR2.3.3 (in alpha))
(Im not trying to do an ad, it's just a way to reproduce the error)

I will send log as son as I can

**Comment by coco875** [comment]
so you try it with connector 31 with removing before .connector folder ?

**Comment by Groupix05** [comment]
I've made a new issue so It's more precise #721

I have the lastest version of Connector and removing .connector crash the game while transforming Hybrid aquatic.
If I launch my game a second time, everything works. But If I do the same on my server, it will always crash
