### ISSUE TITLE
Food bar dissapear

### ISSUE THREAD

**Issue by glea94** [Sinytra/Connector#630]
### Describe the bug

food bar dissapear with the last b1.31

### Steps to reproduce

1.play with b1.30
2.food bar here
3.play with b1.31
4.food bar dissapear

### Additional context

Hi I just update connector to last b1.31 and the food bar is gone.
I downgrade the version to b1.30 and it's there.

For the bars i have overflowing bar for forge, Passive Skill Tree also who give skill for feeding.
I don't have any error message about, it's just not visually there, feeding work.

**Comment by Su5eD** [comment]
Are you playing with any mods or just Connector?

**Comment by BookerCatch** [comment]
Some logs that might help.

[debug.log](https://github.com/Sinytra/Connector/files/13721659/debug.log)
[latest.log](https://github.com/Sinytra/Connector/files/13721660/latest.log)

**Comment by glea94** [comment]
Hi
I play with your 3 mods
Synitra connector, Connector Extras and Forgified Fabric API.
I load the game with Forge last version and add some Fabric mods i can't get with Forge.

**Comment by DigitalData** [comment]
Hi. Looks like I'm experiencing a similar issue. I have the latest connector version for mc 1.20.1. 

Installing either overflowing bars or colourful hearts causes the hunger bar to disappear. Interestingly, the AppleSkin HUD overlay still renders. that might help narrow down the root cause.

I can post a screenshot on request (currently not at my PC).

**Comment by glea94** [comment]
Hi, just giving some news that the 1.32 works, the food bar is there now.
Thank you for the update 🤗
