### ISSUE TITLE
Error code 1 during startup with Yttr

### ISSUE THREAD

**Issue by githubgarry73** [Sinytra/Connector#643]
### Mod Name

Yttr

### Mod Homepage

https://git.sleeping.town/unascribed-mods/Yttr/src/branch/1.20.1

### Describe the bug

Game refuses to start, returns error code 1. No crash report.

### Steps to reproduce

1. Install forge 47.2.0
2. Install Connector beta31, ConnectorExtras 1.8.0, Forgified Fabric API 0.90.7+1.10.3, Yttr 7.736
3. Start minecraft
4. Crash

### Logs

https://mclo.gs/YoysDMN

**Comment by unilock** [comment]
I've forked Yttr to improve the WIP 1.20 port, as well as introduce Sinytra Connector compatibility: https://github.com/unilock/Yttr/tree/1.20.1-connectormod

You'll also need a modified version of Lib39: https://github.com/unilock/Lib39/tree/1.20.1-connectormod

Currently, the mod works on clients, but crashes on dedicated servers due to #991.

**Comment by Su5eD** [comment]
I recommend using unilock's fork, which works on Connector
