### ISSUE TITLE
EventSubclassTransformer fails to locate classes if a ThreadPool is used during `preLaunch`

### ISSUE THREAD

**Issue by melontini** [Sinytra/Connector#644]
### Describe the bug

Same as title.

### Steps to reproduce

1. Launch the game with Andromeda 1.4.1
2. The log bleeds
3. Game launches as normal, functionality unaffected.

### Logs

N/A

### Additional context

This doesn't affect functionality in any way, but this does cause massive log spam.

For some reason EST tries to lookup classes on the ApplicationClassloader instead of the GAME TransformingClassloader, even though it should be set as the context CL by that point.

**Comment by melontini** [comment]
I suppose this could be closed when connector moves to Neo, since EST is no more (🦀)

**Comment by Su5eD** [comment]
From what I can see in the mod code, this seems to have been caused by Andromeda creating its own ForkJoinPool with the **default** thread factory rather than the one configured by Connector, and so the context class loader was never set correctly. However, it seems it has since been updated to use the common pool instead. Is this still an issue?

**Comment by melontini** [comment]
Just tested it. Yes, it still tries to look up the class on AppCl.

**Comment by Su5eD** [comment]
I think I see what's going on, Java can't initialize the factory because it's loaded by a higher classloader
