### ISSUE TITLE
COFH_CORE is incompatible with connector via dedicated server

### ISSUE THREAD

**Issue by Xplodin** [Sinytra/Connector#668]
### Mod Name

cofh_core

### Mod Homepage

https://github.com/CoFH/CoFHCore

### Describe the bug

Cannot join a dedicated server

### Steps to reproduce

1. Add connector + extras + dependencies
2. add cofh_core, plus all thermal mods + thermal extra + redstone arsenal 
3. try joining a local dedicated server or dedicated
...
works fine in SP. once cofh + mods removed it works

### Logs

https://gist.github.com/Xplodin/d128be276827b333ac165d7ae6364935

### Additional context

https://gist.github.com/Xplodin/2e4c3bbfa80ca8b0b4fbb413c61242db - Full debug.log

image of error upon joining world: 
![image](https://github.com/Sinytra/Connector/assets/13007677/c413d935-5d28-4ddd-9d65-faed59188c7c)

**Comment by Su5eD** [comment]
You log shows a lot more mods installed than what you've listed. Please provide a minimal reproducible example. I've tried this out on a server with only the thermal mods and connector, but was unable to reproduce the issue.

> Before reporting, please ensure that:
> - You've installed a **minimal set of mods** required to reproduce the issue.
    Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
    Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
    If you're unsure which mods might be at fault, try using binary search - removing half of installed mods
    repeatedly until the faulty mod is found.

**Comment by DarthCaesium** [comment]
To be fair, CoFH Core is incredibly intrusive and unsafe. It's a complete mess of a core mod that disregards mod compatibility in general, so I'm not surprised. For example, any mod modifying anything to do with the bow doesn't work when CoFH Core is installed, because it uses intrusive mixins on bows for Archer's Paradox that override any other modification on bow behaviour. This is also regardless of whether the user has installed Archer's Paradox. CoFH Core is just a complete mess and trying to support it is not much easier or much more worth it than trying to support Optifine.
