### ISSUE TITLE
Incompatibility with imbued gear

### ISSUE THREAD

**Issue by Tomat777** [Sinytra/Connector#753]
### Mod Name

Bumblezone, imbued gear

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/imbued-gear, https://www.curseforge.com/minecraft/mc-mods/the-bumblezone-forge

### Minecraft version

1.20.1

### Describe the bug

https://github.com/TelepathicGrunt/Bumblezone/issues/338

### Steps to reproduce

in linked issue

### Logs

in linked issue

### Additional context

Fabric version of bumblezone works fine

**Comment by TelepathicGrunt** [comment]
Just to clarify as per on the bug report I gotten:
https://github.com/TelepathicGrunt/Bumblezone/issues/338#issuecomment-1903870589

This issue has *nothing* to do with Bumblezone. Bumblezone is not involved at all here. You will get the crash with that fabric mod alone on forge the moment you damage a tool or something. Anything that calls getMaxDamage will crash due to the fabric mod not made with the forge patch in mind.
