### ISSUE TITLE
Incompatible with the TabTPS mod

### ISSUE THREAD

**Issue by BadGhost520** [Sinytra/Connector#797]
### Mod Name

TabTPS

### Mod Homepage

https://modrinth.com/plugin/tabtps

### Minecraft version

1.20.1

### Describe the bug

The name in the mod is not displayed correctly

### Steps to reproduce

1.Input command:/tps or /tabtps
2.Problem occurs(See picture)(The Image is a screenshot of a single player game)
![2](https://github.com/Sinytra/Connector/assets/122501666/19f72f1d-9632-4d21-a5ff-751f6313d6cd)
Names like “xyz.jpenilla.tabtps.common.message” should not be displayed like this

### Logs

No error output in console

**Comment by mpustovoi** [comment]
That won't be fixed in the near future, I guess.
This mod uses some kind of non-standard implementation of technical translation.
For now, you can use the `Server Tab Info` mod: https://modrinth.com/mod/server-tab-info
Yes, it has much less features. For instance, it doesn't have a TPS display on action bar or a used RAM log for the last 20 minutes, but it copes with its task of displaying the current TPS.
In the settings, you can replace the Tab panel with the mod's TPS panel or bind the display of the TPS window to another button.
Also I recommend to go to mod's config file in `serverconfig` folder of your world set `refreshTicks` to `10` and put this config in `defaultconfigs` in the root folder.

**Comment by Su5eD** [comment]
Unfortunately, this cannot be fixed on our end, as the mod's translation is incompatible with modlauncher's classloading mechanism.
