### ISSUE TITLE
Support for safely declaring Connector, Connextras, or FFAPI as a dependency via a `mods.toml`

### ISSUE THREAD

**Issue by sisby-folk** [Sinytra/Connector#806]
Hi hello there! We publish a few fabric mods on modrinth that we mark as forge compatible due to being on 1.20.1 and working with connector e.g. [Portable Crafting](https://modrinth.com/mod/portable-crafting) or [Tinkerer's Smithing](https://modrinth.com/mod/tinkerers-smithing).

It would be helpful to flag these as missing connector to forge so that when connector isn't installed, you get this screen:

![image](https://github.com/Sinytra/Connector/assets/55819817/34340894-31fd-4ce9-9924-712e8088a857)

but that doesn't crash fabric when loaded there.

Naturally, I achieved the above using a mods.toml:

![image](https://github.com/Sinytra/Connector/assets/55819817/f0bb5998-0ff7-4086-9f09-9dece14ea053)

and a small build.gradle tweak:

![image](https://github.com/Sinytra/Connector/assets/55819817/220471f3-3d10-4172-bf12-200a34f5fcbf)

This works great when connector isn't installed.

Unfortunately, when connector _is_ installed, the mod attempts to load as a regular forge mod, and the whole thing falls apart. You could set the modLoader to lowCodeFML and add a pack.toml, but the result is the same - the fabric.mod.json isn't read by connector, and it's not loaded that way.

Would it be possible to have a mods.toml setup that connector can recognize for this exact purpose?

sidenote, i'm not actually sure if there's a mod ID i can declare for a ffapi dependency - let me know if there is one.

**Comment by Su5eD** [comment]
This is a good idea, although a bit difficult to implement. The catch is that FML doesn't provide us with any way we could prevent mods that have already been discovered from loading. And since the mod is a regular FML mod jar, we can't stop the discoverer from locating it, either.

My approach would be to include a flag in the mod file, something like `connector:fallback = true`, which would then be read by connector to (? somehow ?) remove the mod from the loading list.

**Comment by Su5eD** [comment]
> sidenote, i'm not actually sure if there's a mod ID i can declare for a ffapi dependency - let me know if there is one.

Sure, you can depend on `fabric_api`. All of FFAPI's modules use the upstream modid with `-` dashes replaced by `_` underscores to comply with FML's requirements.

**Comment by Su5eD** [comment]
So, here's how I approached this:

FML's unique mod selector always picks the latest version among duplicate mod IDs, allowing us to abuse it to make sure the Forge mod never loads when Connector is present. Connector will now look for a new `connector:placeholder` property in the mods.toml file to determine whether the mod should be ignored. If the property if present, regardless of its value, Connector will set the mod's version to `0.0`, ensuring the Fabric mod takes priority when FML begins to resolve duplicates.

Creating a placeholder mod should now be as simple as adding the following lines into the `mods.toml` file at the top level.
```toml
[properties]
"connector:placeholder"=true
```
Please also make sure the Fabric and Forge modids match, otherwise FML will try to load both of them at once.
