### ISSUE TITLE
[1.20.1] EssentialGUI crashes when hovering over End Remastered ender eyes.

### ISSUE THREAD

**Issue by KateReller** [Sinytra/Connector#852]
### Mod Name

EssentialGUI

### Mod Homepage

https://modrinth.com/mod/essentialgui

### Minecraft version

1.20.1

### Describe the bug

When hovering over any ender eye from End Remastered, the game crashes.

### Steps to reproduce

1. Open the game.
2. Load a world.
3. Obtain any of the unique ender eyes.
4. Crash.

### Logs

https://mclo.gs/mD3qOfQ

**Comment by Su5eD** [comment]
This is an unfortunate interactions between the two mods. End Remastered marks its ender eye items as [damageable](https://github.com/Team-Remastered/End-Remastered-Forge/blob/aed2f9d7c496e898eb1f9f895bc005a75d4dc204/src/main/java/com/teamremastered/endrem/items/EREnderEye.java#L159), but doesn't set their max damage. As a result, essential gui will try to divide by zero thinking the item's max damage is always non-zero if `isDamageable` returns true.

I'd recommend forwarding this issue to essentialgui so that they can check the max damage before dividing and avoid the crash.
