### ISSUE TITLE
Connector Mixin Forge

### ISSUE THREAD

**Issue by Krimatoria** [Sinytra/Connector#876]
### Minecraft version

1.20.1

### Describe the bug

Mixin

### Steps to reproduce

gigeresque-connector-1.20.1-0.5.62.jar
fabric-api-0.92.0+1.11.3+1.20.1.jar
Connector-1.0.0-beta.37+1.20.1.jar
azurelib-neo-1.20.1-2.0.20.jar
SmartBrainLib-forge-1.20.1-1.13.jar

https://github.com/LlamaLad7/MixinExtras/issues/73 - All the information is here

**Comment by Su5eD** [comment]
This is caused by the Gigeresque mod including the Fabric version of mixinextras, whose modid differs from its forge version. Connector logs this as it's usually a bug in mods, but that is not the case here, as the duplicate mixinextras mod gets disabled/filtered by the split package merger.

You can safely ignore the error; it doesn't have any negative inpact.

**Comment by LlamaLad7** [comment]
I’d still appreciate the warning being removed for mixinextras specifically, it’s not the first time people have come to me about it.

**Comment by Su5eD** [comment]
Ah, I see. In case this is a common occurence, it's highly likely to happen with other mods, too. I think the best solution will be to changing the log level to debug, allowing us to still keep track of these meesages while not confusing users unnecessarily.
