### ISSUE TITLE
incompatibility between Epic Fight and Icarus

### ISSUE THREAD

**Issue by Aurarobe** [Sinytra/Connector#897]
### Mod Name

Icarus

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/icarus

### Minecraft version

1.20.1

### Describe the bug

When run together the mods causes a mixin error making the game crash

### Steps to reproduce

1.add Epic Fight and Icarus (with Trinkets and MidnightLib dependency)
2.run game
3.crashes
...

### Logs

https://gist.github.com/Aurarobe/f8a8f43c07b63b45b279ee2e4af7e500

### Additional context

it seems to be caused by Icarus not being able to run the config file
epic fight runs fine with the Icarus dependencies so it's likely they're not the cause
icarus works fine if epic fight is removed

**Comment by Su5eD** [comment]
This is caused by a mixin conflict between Icarus and Epic Fight. Both Epic Fight's [MixinMouseHandler](https://github.com/Yesssssman/epicfightmod/blob/1.20.1/src/main/java/yesman/epicfight/mixin/MixinMouseHandler.java) and Icarus's [MouseMixin](https://github.com/CammiePone/Icarus/blob/1.20-dev/src/main/java/dev/cammiescorner/icarus/core/mixins/client/MouseMixin.java) target the same method call, which first gets redirected by EpicFight, causing Icarus to crash. Maybe it could be solved by mixin priority of the ModifyArg injector in Icarus, but that is up to the mod author to fix. I recommend reporting this conflict to EF/Icarus.

**Comment by Aurarobe** [comment]
hello, i've found a way to fix the mixin conflict, which is to install this mod https://www.curseforge.com/minecraft/mc-mods/yacl from the description of the mod: "[MidnightLib]): It's mostly bloat and doesn't have a focus on config. This library includes other unwanted features such as cosmetics.". Which seems to have fixed the issue, so I am commenting here incase anyone ever run into this problem aswell
