### ISSUE TITLE
crash with archon

### ISSUE THREAD

**Issue by coco875** [Sinytra/Connector#91]
### Mod Name

Archon

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/archon

### Describe the bug

crash at start

### Steps to reproduce

1. Have connector, ffapi, archon
2. run
3. and see

### Logs

https://pastebin.com/LfxjSCXs

### Additional context

[debug.log](https://github.com/Sinytra/Connector/files/12412415/debug.log)

**Comment by Su5eD** [comment]
I was able to fix the crash by adding the missing accessor in FFAPI.

However, I noticed another issue where the mana hud overlay is not displayed. This is caused by Archon mixing into `Gui#render`, which gets overriden by Forge's class. Instead, they should be using the `HudRenderCallback` event provided by FAPI, which offers the same functionality in a more compatible way.
