### ISSUE TITLE
Trinkets breaks with Blueprint 7.0.1

### ISSUE THREAD

**Issue by milkev** [Sinytra/Connector#919]
### Mod Name

Blueprint 7.0.1

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/blueprint

### Minecraft version

1.20.1

### Describe the bug

When the game is loaded with Blueprint 7.0.1, trinkets slots no longer show up and any trinkets previously equipped are put in the players inventory.

### Steps to reproduce

1. Install Blueprint 7.0.1, Trinkets, Connector and a mod that adds a trinket (such as milkevs essentials(note milkevs essentials also requires connector extras))
2. Load into world, see that trinkets slots do not exist
3. Optionally load into a world without Blueprint first, equip a trinket, then load in with Blueprint installed.
4. Optionally load into the world with Blueprint 7.0.0 and observe trinkets working as expected.

### Logs

https://pastebin.com/nBxjxW7M

**Comment by sisby-folk** [comment]
Confirming that blueprint >=7.0.1 completely bricks all (at least client) reloaders registered through connector. Encountered this after a report on antique atlas 2.2.

The culprit is [client.ReloadableResourceManagerMixin](https://github.com/team-abnormals/blueprint/blob/1.20.x/src/main/java/com/teamabnormals/blueprint/core/mixin/client/ReloadableResourceManagerMixin.java) for us - so it's probably their [https://github.com/team-abnormals/blueprint/blob/1.20.x/src/main/java/com/teamabnormals/blueprint/common/remolder/RemoldedResourceManager.java](https://github.com/team-abnormals/blueprint/blob/1.20.x/src/main/java/com/teamabnormals/blueprint/common/remolder/RemoldedResourceManager.java#L41) in general.

**Comment by RoomAlex68** [comment]
Blueprint 7.0.3 crashes on Connector Beta 40

**Comment by Su5eD** [comment]
@sisby-folk thanks for the hint! After Blueprint replaced the resource manager with their own - which does not implement FAPI's internal interface - the manager's pack type could no longer be determined, preventing FAPI from injecting Fabric mods' reloaders. I made it "guess" the type instead based on available resource namespaces, which should work fine. _I hope._

**Comment by Su5eD** [comment]
Fixed in Forgified Fabric API [0.92.0+1.11.5+1.20.1](https://modrinth.com/mod/forgified-fabric-api/version/0.92.0+1.11.5+1.20.1).

**Comment by sisby-folk** [comment]
![image](https://github.com/Sinytra/Connector/assets/55819817/94b8cfb5-b188-482c-a692-119da2aef728)

![image](https://github.com/Sinytra/Connector/assets/55819817/81bfa306-5399-414f-89c8-3d1c5b451c88)

looks good on my end, cheers!
