### ISSUE TITLE
fabric season don't have the tooltips

### ISSUE THREAD

**Issue by coco875** [Sinytra/Connector#96]
### Describe the bug

in game

### Steps to reproduce

1. have ffapi, connector, fabric season, fabric season delight compat, farmerdelight forge version
2. run
3. put the mouse on the rice for exemple and he don't have the tooltip like in example of the mod

### Additional context

mod link: https://www.curseforge.com/minecraft/mc-mods/fabric-seasons-delight-compat
what I have
![image](https://github.com/Sinytra/Connector/assets/59367621/25ffdca3-3431-445a-b968-48b3425c9cbc)
vs what I should have
![image](https://github.com/Sinytra/Connector/assets/59367621/0e9af4aa-f745-4423-8fd9-85eb9157144e)

**Comment by Su5eD** [comment]
This happens because fabric seasons delight compat is designed to work with Farmer's Delight for fabric. FD's forge and fabric versions differ, and seasons delight compat mod mixins will not apply on the forge version.

Farmer's Delight fabric works fine on connector, so if you want to use fabric seasons compat I recommend using that instead.

**Comment by coco875** [comment]
ok I will try like the mod don't crash I think a bridge can be made
