### ISSUE TITLE
[1.20.1] Adaptive Tooltips crash with Connector

### ISSUE THREAD

**Issue by Starexify** [Sinytra/Connector#989]
### Mod Name

Adaptive Tooltips

### Mod Homepage

https://modrinth.com/mod/adaptive-tooltips

### Minecraft version

1.20.1

### Describe the bug

Mod crashing with Connector at startup

### Steps to reproduce

1. Install Adaptive Tooltips alongside Connector and it crashes.

### Logs

[crash-2024-04-07_11.59.06-client.txt](https://github.com/Sinytra/Connector/files/14896729/crash-2024-04-07_11.59.06-client.txt)
[latest.log](https://github.com/Sinytra/Connector/files/14896731/latest.log)

### Additional context

Just checking for more compatbility👍

**Comment by Su5eD** [comment]
This mods works fine with connector. The crash you are receiving is caused by a loading error from missing dependencies.

![2024-04-07_12 16 37](https://github.com/Sinytra/Connector/assets/51261569/681d1246-d3a8-4583-96a9-c4e4b6f54b83)

> [11:59:06] [Render thread/FATAL]: Error during pre-loading phase
net.minecraftforge.fml.ModLoadingException: Mod �eroughlyenoughitems�r requires �6cloth_config�r �o10.0 or above�r
�7Currently, �6cloth_config�r�7 is �o�nnot installed

Please read the issue template more carefully. For modpack related issues, use the `support` channel on our [discord](https://discord.sinytra.org) server.

> Before reporting, please ensure that:
> - You've installed a **minimal set of mods** required to reproduce the issue.
    Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
    Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
    If you're unsure which mods might be at fault, try using binary search - removing half of installed mods
    repeatedly until the faulty mod is found.

> To upload logs, use an external paste site, such as Github Gist (recommended), Ubuntu Pastebin or Pastebin
